export { default as ClientsSection } from './ClientsSection'
export { default as ContactsSection } from './ContactsSection'
export { default as DashboardSection } from './DashboardSection'
export { default as OpportunitiesSection } from './OpportunitiesSection'
export { default as InteractionsSection } from './InteractionsSection'
export { default as ProductsSection } from './ProductsSection'
export { default as SubscriptionsSection } from './SubscriptionsSection'
export { default as InvoicesSection } from './InvoicesSection'
export { default as QuotesSection } from './QuotesSection'
export { default as ReportsSection } from './ReportsSection'
export { default as SettingsSection } from './SettingsSection'
export { default as HistorySection } from './HistorySection'
export { default as ComplianceSection } from './ComplianceSection'
export { default as PricingSection } from './PricingSection'
export { default as RulesSection } from './RulesSection'
export { default as TemplatesSection } from './TemplatesSection'

