-- AlterTable
ALTER TABLE "QuotationConfig" ADD COLUMN     "heroTituloMain" TEXT NOT NULL DEFAULT 'PROPUESTA DE COTIZACIÓN',
ADD COLUMN     "heroTituloSub" TEXT NOT NULL DEFAULT 'PÁGINA CATÁLOGO DINÁMICA';
